--Autor: Erick Octavio Nolasco Machuca
--Practica 6

--Crear la base de datos Guarderia
Create database Guarderia
on primary
(
	Name= 'Guarderia.MDF',
	filename= 'C:\TBD2019\Guarderia.MDF'
)
Log on 
(
	Name= 'Guarderia.LDF',
	filename= 'C:\TBD2019\Guarderia.LDF'
);
--Usar la base de datos
use Guarderia

--Crear la tabla PADRES_TUTORES
CREATE TABLE PADRE_TUTORES
(
	ID_PADRES numeric(18,0) not null,
	PADRE_NOMBRE varchar(50) not null,
	PADRE_HORTRAB varchar(30),
	PADRE_DOM varchar(18) not null,
	PADRE_TELCAS varchar(18),
	PADRE_TELCEL varchar(18),
	PADRE_TELOTRO varchar (18)
)
--Crear la tabla REGISTRO_INCIDENCIAS
CREATE TABLE REGISTRO_INCIDENCIAS
(
	ID_INCIDENCIAS INT IDENTITY(5,1)not null,
	ID_ALUMNO INT not null,
	TIPO_ID char(1) not null,
	OBSERVACIONES varchar(50),
	FECHA datetime
)
--Crear la tabla ALUMNO
CREATE TABLE ALUMNO
(
	ID_ALUMNO INT NOT NULL,
	SALA_ID INT NOT NULL,
	ALU_EDAD INT,
	ALU_SEXO VARCHAR(1),
	ALUMN_FECHANAC DATETIME,
	ALUMN_LUGARNAC VARCHAR(30),
	ALUMN_FOTO IMAGE,
	ALUMN_SERMED VARCHAR(30),
	FECHA_ALTA DATETIME,
	OBSERVACIONES VARCHAR(100),
	ID_MAMA NUMERIC(18,0),
	ID_PAPA NUMERIC(18,0)
)
--CREAR TABLA SALAS
CREATE TABLE SALAS
(
	SALA_ID INT NOT NULL,
	SALA_NOMBRE VARCHAR(20),
	MTRO_NOMBRE VARCHAR(50) NOT NULL,
	SALA_MAXALUMN INT
)
--CREAR TABLA HISTORIA_CLINICA
CREATE TABLE HISTORIA_CLINICA
(
	ID_ALUMNO INT NOT NULL,
	FECHA VARCHAR(12),
	PROPORCIONA_INFORMACION VARCHAR(35),
	VARICELA CHAR(1),
	SARAMPION CHAR(1),
	RUBIOLA CHAR(1)
)

--Crear llave primaria ALUMNO
Alter table Alumno add constraint PK_ALUMNO PRIMARY KEY (ID_ALUMNO) 
GO
--Crear llave primaria HISTORIA_CLINICA
Alter table HISTORIA_CLINICA add constraint PK_HISTORIA_CLINICA PRIMARY KEY (ID_ALUMNO) 
GO
--Crear llave primaria PADRE_TURORES
Alter table PADRE_TUTORES add constraint PK_PADRE_TUTORES PRIMARY KEY (ID_PADRES) 
GO
--Crear llave primaria SALAS
Alter table SALAS add constraint PK_SALAS PRIMARY KEY (SALA_ID) 
GO
--Crear llave primaria REGISTRO_INCIDENCIAS
Alter table REGISTRO_INCIDENCIAS add CONSTRAINT PK_REGISTRO_INCIDENCIAS PRIMARY KEY (ID_INCIDENCIAS);

--CREAR LLAVE FORANEA ALUMNO-PADRES_TUTORES
Alter table ALUMNO ADD CONSTRAINT FK_ALU_PADRES FOREIGN KEY (ID_MAMA) REFERENCES PADRE_TUTORES(ID_PADRES);
Alter table ALUMNO ADD CONSTRAINT FK_ALU_PADRES_papa FOREIGN KEY (ID_PAPA) REFERENCES PADRE_TUTORES(ID_PADRES);
--CREAR LLAVE FORANEA ALUMNO - SALAS
Alter table ALUMNO ADD CONSTRAINT FK_ALU_SALAS FOREIGN KEY (SALA_ID) REFERENCES SALAS(SALA_ID);
--CREAR LLAVE FORANEA REGISTRO_INCIDENCIAS-ALUMNO
Alter table REGISTRO_INCIDENCIAS ADD CONSTRAINT FK_REG_ALUMNOS FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO);
--CREAR LLAVE FORANEA ALUMNO - HISTORIA_CLINICA; HISTORIA_CLINICA-ALUMNO
Alter table ALUMNO ADD CONSTRAINT FK_ALU_HISTORIA_CLINICA FOREIGN KEY (ID_ALUMNO) REFERENCES HISTORIA_CLINICA(ID_ALUMNO);
Alter table HISTORIA_CLINICA ADD CONSTRAINT FK_HIS_ALUMNO FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO);