--Autor: Erick Octavio Nolasco Machuca

---Crear la base de datos Secreataria de salud
create database SecretariaS
On primary
(
Name= 'SecretariaS.MDF',
FileName= 'C:\TBD2019\SecretariaS.MDF',
SIZE= 12 MB,
Maxsize= unlimited,
filegrowth= 10%
)
Log on
(
Name= 'SecretariaS.LDF',
FileName= 'C:\TBD2019\SecretariaS.LDF',
SIZE= 12 MB,
Maxsize= unlimited,
filegrowth= 10%
)
GO
USE SecretariaS;
--Crear tabla Hospitales
CREATE TABLE HOSPITAL
(
	IDHOSPITAL TINYINT IDENTITY(1,1) NOT NULL,
	H_NOMBRE VARCHAR(20),
	H_DIRECCION varchar(20),
	H_TELEFONO varchar(10),
	H_CACAMAS tinyint ,
	H_CEDULA VARCHAR(20),
	H_IDLAB tinyint
);
--Crear tabla SALA
CREATE TABLE SALA
(
	IDSALA TINYINT IDENTITY(1,1) NOT NULL,
	S_NOMBRE VARCHAR(20),
	S_CAMAS tinyint ,
	S_IDHOSPITAL TINYINT
);
-- Crear tabla Médico
CREATE TABLE MEDICO
(
	CEDULA VARCHAR(20)  NOT NULL,
	M_NOMBRE VARCHAR(45),
	M_ESPECIALIDAD varchar(20),
	M_IDHOSPITAL TINYINT not null,
	M_IDPACIENTE TINYINT
);
--Crear tabla LABORATORIO
CREATE TABLE LABORATORIO
(
	IDLAB TINYINT IDENTITY(1,1) NOT NULL,
	L_NOMBRE VARCHAR(20),
	L_DIRECCION varchar(20),
	L_TELEFONO varchar(10),
	L_IDHOSPITAL TINYINT
);
--Crear tabla PACIENTE
CREATE TABLE PACIENTE
(
	IDPACIENTE TINYINT IDENTITY(1,1) NOT NULL,
	P_NOMBRE VARCHAR(45),
	P_DIRECCION varchar(20),
	P_NOREGISTRO INT,
	P_NOCAMA TINYINT,
	P_NACIMIENTO DATETIME,
	P_SEXO varchar(10),
	P_IDSALA TINYINT,
	P_CEDULA VARCHAR(20)
);
--CREAR TABLA DIAGNOSTICO
CREATE TABLE DIAGNOSTICO
(
	IDDIAGNOSTICO TINYINT IDENTITY(1,1) NOT NULL,
	D_TIPO VARCHAR(20),
	D_COMPLICACIONES varchar(255),
	D_IDPACIENTE TINYINT
);

--LLAVE PRIMARIA HOSPITALES
ALTER TABLE HOSPITAL ADD CONSTRAINT PK_HOSPITAL PRIMARY KEY(IDHOSPITAL);
--LLAVE PRIMARIA SALA
ALTER TABLE SALA ADD CONSTRAINT PK_SALA PRIMARY KEY(IDSALA);
--LLAVE PRIMARIA MEDICO
ALTER TABLE MEDICO ADD CONSTRAINT PK_MEDICO PRIMARY KEY(CEDULA,M_IDHOSPITAL);
--LLAVE PRIMARIA LABORATORIO
ALTER TABLE LABORATORIO ADD CONSTRAINT PK_LABORATORIO PRIMARY KEY(IDLAB);
--LLAVE PRIMARIA PACIENTE
ALTER TABLE PACIENTE ADD CONSTRAINT PK_PACIENTE PRIMARY KEY(IDPACIENTE);
--LALVE PRIMARIA DIAGNOSTICO
ALTER TABLE DIAGNOSTICO ADD CONSTRAINT PK_DIAGNOSTICO PRIMARY KEY(IDDIAGNOSTICO);

--CADA HOSPITAL TIENE VARIAS SALAS
ALTER TABLE SALA ADD CONSTRAINT FK_HO_SALAS FOREIGN KEY(S_IDHOSPITAL) REFERENCES HOSPITAL(IDHOSPITAL);
--CADA HOSPITAL TRABAJA CON MUCHOS LABORATORIOS Y CADA LABORATORIO PRESTA SERVICIO A MAS DE UN HOSPITAL
ALTER TABLE LABORATORIO ADD CONSTRAINT FK_LAB_HOSPITAL FOREIGN KEY(L_IDHOSPITAL) REFERENCES HOSPITAL(IDHOSPITAL);
ALTER TABLE HOSPITAL ADD CONSTRAINT FK_HO_LABORATORIO FOREIGN KEY (H_IDLAB) REFERENCES LABORATORIO(IDLAB);
--UN PACIENTE PUEDE ESTAR INTERNADO EN UNA UNICA SALA
ALTER TABLE PACIENTE ADD CONSTRAINT FK_PA_SALA FOREIGN KEY(P_IDSALA) REFERENCES SALA(IDSALA);
--CADA PACIENTE PUEDE SER ATENDIDO POR MAS DE UN MEDICO Y CADA MEDICO PUEDE ATENDER A MAS DE UN PACIENTE
ALTER TABLE MEDICO ADD CONSTRAINT FK_ME_PACIENTE FOREIGN KEY(M_IDPACIENTE) REFERENCES PACIENTE(IDPACIENTE);
--CADA PACIENTE PUEDE TENER MUCHOS DIAGNOSTICOS
ALTER TABLE DIAGNOSTICO ADD CONSTRAINT FK_DIA_PACIENTE FOREIGN KEY(D_IDPACIENTE) REFERENCES PACIENTE(IDPACIENTE);
--FECHA DIAGNOSTICO
ALTER TABLE DIAGNOSTICO ADD FECHA DATE;
--CONSTRAINT DEFAULT
ALTER TABLE DIAGNOSTICO ADD CONSTRAINT DF_DIA_FECHA DEFAULT getdate() FOR FECHA;
--CONSTRAINT CHECK
ALTER TABLE SALA ADD CONSTRAINT CHK_SAL_CAMAS CHECK (S_CAMAS>0);