--Autor: Erick Octavio Nolasco Machua
--Fecha: 12/09/2019

--PONER CONSTRAINT DE PK A LAS TABLAS

Alter table Alumnos add constraint PK_ALUMNOS PRIMARY KEY (NOCTRL) 
GO

alter table TAREAS_ENTREGADAS ADD CONsTRAINT PK_TAREAENTREGADAS PRIMARY KEY(NOCONTROL,IDTAREA)
GO
Alter table TAREAS add constraint PK_TAREAS PRIMARY KEY (IDTAREA) 
GO

ALTER TABLE UNIDADES ADD CONSTRAINT PK_UNIDAD PRIMARY KEY(IDUNIDAD);

Alter table TAREAS_ENTREGADAS ADD CONSTRAINT FK_TE_ALUMNOS FOREIGN KEY (NOCONTROL) REFERENCES Alumnos(NOCTRL);

Alter table TAREAS_ENTREGADAS ADD CONSTRAINT FK_TE_TAREAS FOREIGN KEY(IDTAREA) REFERENCES TAREAS (IDTAREA);

Alter table TAREAS ADD CONSTRAINT FK_UNI_TAREAS FOREIGN KEY (IDUNIDAD) REFERENCES UNIDADES(IDUNIDAD);

--constraint de check
ALTER TABLE TAREAS ADD CONSTRAINT CH_TAREAS CHECK (T_CALMAX>0 AND T_CALMAX < 100);

--CONSTRAINT DE DEFAULT
ALTER TABLE Alumnos ADD CONSTRAINT DF_ALUMNOS_EDAD DEFAULT 18 FOR EDAD;