-- Practica 3
--Autor: Erick Octavio Nolasco Machuca 17401029
--Fecha:09/09/2019
use TBD2019_GA
go

--crear tabla
create table Alumnos
(
	NOCTRL varchar(8) NOT NULL, 
	NOMBRE VARCHAR(30),
	APEPAT VARCHAR(20),
	APEMAT VARCHAR(30),
	EDAD TINYINT
);
-- 2. CREAR LA TABLA UNIDADES 10/09/2019
CREATE TABLE UNIDADES
(
	IDUNIDAD TINYINT IDENTITY(1,1) NOT NULL,
	NOMBREUNIDAD VARCHAR(100)
)
--3. CREAR LA TABLA TAREAS
CREATE TABLE TAREAS
(
	IDTAREA SMALLINT IDENTITY(1,1) NOT NULL,
	T_NOMBRE VARCHAR(25),
	T_CALMAX TINYINT,
	T_FECENT DATE,
	IDUNIDAD TINYINT NOT NULL,
	T_DESCRIPCION VARCHAR(400)
);
--4 CREAR LA TABLA TAREAS ENTREGADAS
CREATE TABLE TAREAS_ENTREGADAS
(
	NOCONTROL VARCHAR(8) NOT NULL,
	IDTAREA SMALLINT NOT NULL,
	TE_CALOBTENIDA TINYINT
);