--Autor: Erick Octavio Nolasco Machuca
-- Practica 8

create database Restaurant
On primary
(
Name= 'Restaurant.MDF',
FileName= 'C:\TBD2019\Restaurant.MDF',
SIZE= 12 MB,
Maxsize= unlimited,
filegrowth= 10%
)

Log on
(
Name= 'Restaurant.LDF',
FileName= 'C:\TBD2019\Restaurant.LDF',
SIZE= 12 MB,
Maxsize= unlimited,
filegrowth= 10%
)
GO

--Crear tabla INGREDIENTES
CREATE TABLE INGREDIENTES
(
	ING_ID INT IDENTITY(1,1)NOT NULL PRIMARY KEY,
	ING_NOMBRE VARCHAR(50)
);

--Crear tabla CHEF
CREATE TABLE CHEF
(
	CHEF_ID INT IDENTITY(1,1)NOT NULL PRIMARY KEY,
	CHEF_NOMBRE VARCHAR(80),
	CHEF_ESPECIALIDAD VARCHAR(20)
);
--Crear tabla TIPO_RECETAS
CREATE TABLE TIPO_RECETAS
(
	TIPO_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TIPO_DESCRIPCION VARCHAR(50)
);
--Crear tabla RECETAS
CREATE TABLE RECETAS
(
	REC_ID INT IDENTITY(10,10)NOT NULL PRIMARY KEY,
	REC_NOMBRE VARCHAR(100),
	CHEF_ID INT REFERENCES CHEF(CHEF_ID),
	REC_FECHA DATE,
	TIPO_ID INT REFERENCES TIPO_RECETAS(TIPO_ID),
	REC_MODO VARCHAR(2000)
);
-- Crear tabla DET_RECETAS
CREATE TABLE DET_RECETAS
(
	REC_ID INT NOT NULL REFERENCES RECETAS(REC_ID),
	ING_ID INT NOT NULL REFERENCES INGREDIENTES(ING_ID),
	ING_CANTIDAD INT,
	ING_MEDIDA VARCHAR(6)
);
alter table DET_RECETAS ADD CONsTRAINT PK_TAREAENTREGADAS PRIMARY KEY(REC_ID,ING_ID);
